config/routes.rb
Rails.application.routes.draw do
  get 'thanks/stores'

  get 'thanks/products'

  get 'thanks/deals'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :Product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :store
  has_many :deals
end

app/models/store.rb
class Store < ActiveRecord::Base
    has_many :products
    public def name_with_id
        "#{s_name} (#{id})"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  def stores
        @stores = Store.all

  end

  def products
    @store_id = params[:store][:id]
    @products = Product.where("store_id = ?", @store_id)
  end

  def deals
    @product_id = params[:product][:id]
    @deals = Deal.where("product_id = ?", @product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThanksGiving</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thanks/deals.html.erb
<h1>Thanks#deals</h1>
<p>Find me in app/views/thanks/deals.html.erb</p>
<table id="deals">
  <thead>
    <tr>
      <th>name</th>
      <th>price</th>
      <th>expires</th>
      
    </tr>
  </thead>
  <% @deals.each do |deal| %>
    <tr>
      <td>
        <%= deal.d_name %>
      </td>
      <td>
        <%= deal.price %>
      </td>
      <td>
        <%= deal.expires %>
      </td>
     
    </tr>
  <% end %>
</table>

app/views/thanks/products.html.erb
<h1>List Of Products</h1>
<%= form_tag "/thanks/deals", method: :get do %>
  <%= collection_select(:product, :id, @products.all, :id, :p_name) %>
  <%= submit_tag "Select Product and Proceed" %>
<% end %>
<br/>
<%= link_to 'Back to Stores', thanks_stores_path %>

app/views/thanks/stores.html.erb
<h1>Thanks#stores</h1>
<p>Find me in app/views/thanks/stores.html.erb</p>
<h1>List Of Stores</h1>
<%= form_tag "/thanks/products", method: :get do  %>
  <%= collection_select(:store, :id, @stores.all, :id, :name_with_id) %>
  <%= submit_tag "Select Store and Proceed" %>
<% end %>